server:
  port: 7110
  error:
    include-stacktrace: on_trace_param
spring:
  application:
    name: e-commerce-item
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/db_ecommerce
    username: ecommerce
    password: ecommerce
  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    drop-first: false
    default-schema: sc_ecommerce_item
    database-change-log-table: ecommerce_item_changelog
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

ecommerce:
  cdn-url: http://localhost:7120

pageable:
  default:
    page-size: 10
    page: 0
